name: build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  createAndTestCRA:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn run build
      - run: yarn run lint
