name: release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  createAndTestCRAFromNpm:
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn run build
      - run: yarn run lint
